config/routes.rb
Secretary::Application.routes.draw do
  resources :clients

  root :to => 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base

  def name
    [first_name, last_name].compact.join(" ")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for @client do |f|
  -if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :phone1
    = f.text_field :phone1
  .field
    = f.label :phone2
    = f.text_field :phone2
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :street_address
    = f.text_field :street_address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.text_field :zip
  .field
    = f.label :job_notes
    = f.text_area :job_notes
  .field
    = f.label :access_notes
    = f.text_area :access_notes
  .field
    = f.label :schedule_notes
    = f.text_field :schedule_notes
  .field
    = f.label :scheduled_estimate_time
    = f.datetime_select :scheduled_estimate_time
  .field
    = f.label :scheduled_job_time
    = f.datetime_select :scheduled_job_time
  .field
    = f.label :found_us_via
    = f.text_field :found_us_via
  .field
    = f.label :insanity_level
    = f.number_field :insanity_level
  .actions
    = f.submit 'Save'

app/views/clients/edit.html.haml
%h1
  = link_to('Clients', clients_path)
  &rarr;
  = link_to @client.name, @client


= render 'form'

= link_to 'View this Client', @client
or 
= link_to 'View All', clients_path

app/views/clients/index.html.haml
%h1 Clients

%table
  %tr
    %th Name
    %th Phone
    %th Email
    %th Street address
    %th Scheduled Estimate Time
    %th Scheduled Job Time    
    %th Insanity

  - @clients.each do |client|
    %tr
      %td= link_to(client.name, client)
      %td= client.phone1
      %td= mail_to(client.email)
      %td= client.street_address
      %td= client.scheduled_estimate_time.stamp("Sat, Jan 1 at 01:00 AM")
      %td= client.scheduled_job_time.stamp("Sat, Jan 1 at 01:00 AM")
      %td= client.insanity_level      

%br

= link_to 'New Client', new_client_path

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'View all Clients', clients_path

app/views/clients/show.html.haml
%h1
  = link_to('Clients', clients_path)
  &rarr;
  = @client.name


%p
  %b Phone1:
  = @client.phone1
%p
  %b Phone2:
  = @client.phone2
%p
  %b Email:
  = mail_to(@client.email)
%p
  %b Street address:
  = @client.street_address
%p
  %b City:
  = @client.city
%p
  %b State:
  = @client.state
%p
  %b Zip:
  = @client.zip
%p
  %b Job notes:
  = @client.job_notes
%p
  %b Access notes:
  = @client.access_notes
%p
  %b Schedule notes:
  = @client.schedule_notes
%p
  %b Scheduled estimate time:
  = @client.scheduled_estimate_time
%p
  %b Scheduled job time:
  = @client.scheduled_job_time
%p
  %b Found us via:
  = @client.found_us_via
%p
  %b Insanity level:
  = @client.insanity_level

%p
  = link_to "Edit #{@client.first_name}", edit_client_path(@client)
  or 
  = link_to 'View All Clients', clients_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secretary</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>